version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Starting build...
      - ls -la    # <-- This lists files, verifying source is present

artifacts:
  files:
    - '**/*'     # Upload all files in repo
  discard-paths: yes
